// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: value.proto

package trade

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type OrderStatus int32

const (
	OrderStatus_open     OrderStatus = 0
	OrderStatus_canceled OrderStatus = 1
	OrderStatus_done     OrderStatus = 2
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "open",
		1: "canceled",
		2: "done",
	}
	OrderStatus_value = map[string]int32{
		"open":     0,
		"canceled": 1,
		"done":     2,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_value_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_value_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_value_proto_rawDescGZIP(), []int{0}
}

type Status int32

const (
	Status_pending Status = 0
	Status_failure Status = 1
	Status_success Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "pending",
		1: "failure",
		2: "success",
	}
	Status_value = map[string]int32{
		"pending": 0,
		"failure": 1,
		"success": 2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_value_proto_enumTypes[1].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_value_proto_enumTypes[1]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_value_proto_rawDescGZIP(), []int{1}
}

type E int32

const (
	E_account_not_found E = 0
)

// Enum value maps for E.
var (
	E_name = map[int32]string{
		0: "account_not_found",
	}
	E_value = map[string]int32{
		"account_not_found": 0,
	}
)

func (x E) Enum() *E {
	p := new(E)
	*p = x
	return p
}

func (x E) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (E) Descriptor() protoreflect.EnumDescriptor {
	return file_value_proto_enumTypes[2].Descriptor()
}

func (E) Type() protoreflect.EnumType {
	return &file_value_proto_enumTypes[2]
}

func (x E) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use E.Descriptor instead.
func (E) EnumDescriptor() ([]byte, []int) {
	return file_value_proto_rawDescGZIP(), []int{2}
}

type AccountScope int32

const (
	AccountScope_order         AccountScope = 0
	AccountScope_order_read    AccountScope = 1
	AccountScope_order_assign  AccountScope = 2 // order_update
	AccountScope_order_take    AccountScope = 3 // order_update just first assign
	AccountScope_product       AccountScope = 10
	AccountScope_product_read  AccountScope = 11
	AccountScope_pipeline      AccountScope = 20
	AccountScope_pipeline_read AccountScope = 21
	AccountScope_agent         AccountScope = 30
	AccountScope_agent_read    AccountScope = 31
	AccountScope_report_read   AccountScope = 40
)

// Enum value maps for AccountScope.
var (
	AccountScope_name = map[int32]string{
		0:  "order",
		1:  "order_read",
		2:  "order_assign",
		3:  "order_take",
		10: "product",
		11: "product_read",
		20: "pipeline",
		21: "pipeline_read",
		30: "agent",
		31: "agent_read",
		40: "report_read",
	}
	AccountScope_value = map[string]int32{
		"order":         0,
		"order_read":    1,
		"order_assign":  2,
		"order_take":    3,
		"product":       10,
		"product_read":  11,
		"pipeline":      20,
		"pipeline_read": 21,
		"agent":         30,
		"agent_read":    31,
		"report_read":   40,
	}
)

func (x AccountScope) Enum() *AccountScope {
	p := new(AccountScope)
	*p = x
	return p
}

func (x AccountScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountScope) Descriptor() protoreflect.EnumDescriptor {
	return file_value_proto_enumTypes[3].Descriptor()
}

func (AccountScope) Type() protoreflect.EnumType {
	return &file_value_proto_enumTypes[3]
}

func (x AccountScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountScope.Descriptor instead.
func (AccountScope) EnumDescriptor() ([]byte, []int) {
	return file_value_proto_rawDescGZIP(), []int{3}
}

var File_value_proto protoreflect.FileDescriptor

var file_value_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74,
	0x72, 0x61, 0x64, 0x65, 0x2a, 0x2f, 0x0a, 0x0b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x08, 0x0a, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x10, 0x00, 0x12, 0x0c, 0x0a,
	0x08, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x65, 0x64, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x64,
	0x6f, 0x6e, 0x65, 0x10, 0x02, 0x2a, 0x2f, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x0b, 0x0a, 0x07, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07,
	0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x10, 0x02, 0x2a, 0x1a, 0x0a, 0x01, 0x45, 0x12, 0x15, 0x0a, 0x11, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x6e, 0x6f, 0x74, 0x5f, 0x66, 0x6f, 0x75, 0x6e, 0x64,
	0x10, 0x00, 0x2a, 0xb7, 0x01, 0x0a, 0x0c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x63,
	0x6f, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x10, 0x00, 0x12, 0x0e,
	0x0a, 0x0a, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x10, 0x01, 0x12, 0x10,
	0x0a, 0x0c, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x10, 0x02,
	0x12, 0x0e, 0x0a, 0x0a, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x74, 0x61, 0x6b, 0x65, 0x10, 0x03,
	0x12, 0x0b, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x10, 0x0a, 0x12, 0x10, 0x0a,
	0x0c, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x10, 0x0b, 0x12,
	0x0c, 0x0a, 0x08, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x10, 0x14, 0x12, 0x11, 0x0a,
	0x0d, 0x70, 0x69, 0x70, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x10, 0x15,
	0x12, 0x09, 0x0a, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x10, 0x1e, 0x12, 0x0e, 0x0a, 0x0a, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x10, 0x1f, 0x12, 0x0f, 0x0a, 0x0b, 0x72,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x10, 0x28, 0x42, 0x18, 0x5a, 0x16,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x62, 0x6e, 0x75, 0x6d,
	0x2f, 0x74, 0x72, 0x61, 0x64, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_value_proto_rawDescOnce sync.Once
	file_value_proto_rawDescData = file_value_proto_rawDesc
)

func file_value_proto_rawDescGZIP() []byte {
	file_value_proto_rawDescOnce.Do(func() {
		file_value_proto_rawDescData = protoimpl.X.CompressGZIP(file_value_proto_rawDescData)
	})
	return file_value_proto_rawDescData
}

var file_value_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_value_proto_goTypes = []interface{}{
	(OrderStatus)(0),  // 0: trade.OrderStatus
	(Status)(0),       // 1: trade.Status
	(E)(0),            // 2: trade.E
	(AccountScope)(0), // 3: trade.AccountScope
}
var file_value_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_value_proto_init() }
func file_value_proto_init() {
	if File_value_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_value_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_value_proto_goTypes,
		DependencyIndexes: file_value_proto_depIdxs,
		EnumInfos:         file_value_proto_enumTypes,
	}.Build()
	File_value_proto = out.File
	file_value_proto_rawDesc = nil
	file_value_proto_goTypes = nil
	file_value_proto_depIdxs = nil
}
